ifneq ($(CONFIG_IFX_PPA_D4_DUALCORE),y)
  obj-$(CONFIG_IFX_PPA_DATAPATH)+= ifxmips_ppa_lite_datapath_danube_d4.o
endif
obj-$(CONFIG_IFX_PPA_DATAPATH)	+= ifxmips_ppa_datapath_danube_d4.o
obj-$(CONFIG_IFX_PPA_DATAPATH)	+= ifxmips_ppa_hal_danube_d4.o
