#!/bin/sh
usage() {
echo "$0 binary_file_name start_address"
}

if [ "$#" -ne 2 ]
then
	usage
	exit 1
elif [ ! -f $1 ]
then
	echo "cannot open $1"
	exit 1
fi

START_ADDRESS=$2
BINARY_FILE=$1
SOURCE_FILE=${BINARY_FILE}.txt

#generate the ascii-representd binary file
#echo "@"$START_ADDRESS >${SOURCE_FILE}
hexdump -v -e '4/1 "%02x""\n"' ${BINARY_FILE} >${SOURCE_FILE}
rm -f ${SOURCE_FILE}.tt
echo "@"$START_ADDRESS>${SOURCE_FILE}.tt
cat ${SOURCE_FILE}>>${SOURCE_FILE}.tt

#split it into four banks
#for (( i=0 ; i<=3 ; i++ ))
#do
#	rm -f ${SOURCE_FILE}.$i
#	echo "@"$START_ADDRESS >${SOURCE_FILE}.$i
#done
#awk -F ""  '{printf("%s%s\n", $1,$2)}' < ${SOURCE_FILE} >> ${SOURCE_FILE}.3
#awk -F ""  '{printf("%s%s\n", $3,$4)}' < ${SOURCE_FILE} >> ${SOURCE_FILE}.2
#awk -F ""  '{printf("%s%s\n", $5,$6)}' < ${SOURCE_FILE} >> ${SOURCE_FILE}.1
#awk -F ""  '{printf("%s%s\n", $7,$8)}' < ${SOURCE_FILE} >> ${SOURCE_FILE}.0
